---

name: Run Terraform code checks
run-name: "run-terraform-code-checks, changes made by ${{ github.actor }}"

on:
  pull_request:
  workflow_dispatch:
jobs:
  run-terraform-code-checks:
    runs-on: k8s-ci-xsmall
    container: ubuntu:23.04
    permissions:
      contents: write
    defaults:
      run:
        shell: bash

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up environment
        run: apt-get update && apt-get install -y make unzip ca-certificates wget git

      - name: Set up terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
          terraform_version: 1.4.6

      - name: Set up tflint
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.46.0

      - name: Set up tfsec
        run: >
          wget -O /usr/local/bin/tfsec https://github.com/aquasecurity/tfsec/releases/download/v1.28.0/tfsec-linux-amd64
          && chmod +x /usr/local/bin/tfsec

      - name: Set up terraform-docs
        run: >
          wget -O /tmp/terraform-docs.tar.gz https://terraform-docs.io/dl/v0.16.0/terraform-docs-v0.16.0-$(uname)-amd64.tar.gz
          && tar -xzf /tmp/terraform-docs.tar.gz -C /tmp
          && mv /tmp/terraform-docs /usr/local/bin/terraform-docs && chmod +x /usr/local/bin/terraform-docs

      - name: Init
        run: make init
        env:
          # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
          GITHUB_TOKEN: ${{ github.token }}

      - name: Validate
        run: make validate

      - name: Format
        run: make fmt TERRAFORM_FMT_ARGS="-list=true -write=true -diff"
      
      - name: Lint
        run: make lint

      - name: Generate docs
        run: make docs

      # doesn't work: https://github.com/actions/checkout/issues/363
      - name: Commit README.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: 'README.md'
          commit_message: Autogenerated module docs
